### ISSUE TITLE
Please assign a license and include a license file

### ISSUE THREAD

**Issue by lmf-mx** [nohwnd/CountdownScreensaver#1]
There is no no default license on GitHub, leaving ambiguity about the allowed usage of code not explicitly licensed. https://help.github.com/articles/licensing-a-repository/

Could you please add a license file?

Thanks

**Comment by nohwnd** [comment]
Hello, I used MIT license. If you need more help please let me know.

**Comment by lmf-mx** [comment]
Perfect, thanks!
